name: Kevan
favicon: null
layout_spectrum: 0.5427070837467909
typography_spectrum: 0.41594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5027093330863863
  lightness: 0.0947993469890207
  saturation: 0.19394841301254928
  rhythmicContrast: 0.8776086021680385
purpose: []
